[project]
name = "presence-form-automation"
version = "0.1.0"
description = "Automates Presence.io form submissions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.2",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "selenium>=4.40.0",
]
